// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBg6_VMzTiU_ZbpVUajphSOIm9_wefjI8',
    appId: '1:262396420415:web:51539d837ce2e550b1738a',
    messagingSenderId: '262396420415',
    projectId: 'timely-ca8ad',
    authDomain: 'timely-ca8ad.firebaseapp.com',
    storageBucket: 'timely-ca8ad.appspot.com',
    measurementId: 'G-V9Y4WJKKCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0wN6mkFFbizc_pa2qEeTVccyJGR4bdco',
    appId: '1:262396420415:android:7fd6e7fd6350489db1738a',
    messagingSenderId: '262396420415',
    projectId: 'timely-ca8ad',
    storageBucket: 'timely-ca8ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxF2T9m_dARUBzOq9Ni0YIbN42AVu0bHI',
    appId: '1:262396420415:ios:9812feb297d9d6d3b1738a',
    messagingSenderId: '262396420415',
    projectId: 'timely-ca8ad',
    storageBucket: 'timely-ca8ad.appspot.com',
    iosClientId: '262396420415-49rvsfl11qgeg6lttaqs4368f8du2bpg.apps.googleusercontent.com',
    iosBundleId: 'com.gettimelyapp.mobile.timely',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxF2T9m_dARUBzOq9Ni0YIbN42AVu0bHI',
    appId: '1:262396420415:ios:9812feb297d9d6d3b1738a',
    messagingSenderId: '262396420415',
    projectId: 'timely-ca8ad',
    storageBucket: 'timely-ca8ad.appspot.com',
    iosClientId: '262396420415-49rvsfl11qgeg6lttaqs4368f8du2bpg.apps.googleusercontent.com',
    iosBundleId: 'com.gettimelyapp.mobile.timely',
  );
}
